ynab:
  access_token: "s3pt_Lg1vnXZSZzZUOWWmQkzhjwCapkClloe3ZqH1e8"
  budget_id: "last-used" # This tells it to use your most recent budget

enable_banking:
  app_id: "12f35a3a-8a16-42bf-9228-98d3bf640636"
  private_key: |
    -----BEGIN RSA PRIVATE KEY-----
 MIIJQQIBADANBgkqhkiG9w0BAQEFAASCCSswggknAgEAAoICAQCtyTEadYJqwMME
fG9FefYCz4/Sgy8n8Ry7qNSNaObLeJCCuA8emNAv17xSpoV04nAp4C+y2G/3yTVa
TgY3Ffkf2ZWK0Ihuj6HFzxW2LqxTvK0PlV0w+hhG5nYq+tIiLi2GmrBn2FjWNtuu
6qYts0P1r4lA/qvOhJlEEx/5CuYcWoCRjO0hOvQvZ2KTILS/aIBokjX0xGvUbEmY
UtpllEz/nkiqaCMfIreu2xoborlGI01mPzR0fTMGE3enzxLVUkWL5JxMacAKO+OY
/S0hGXcg8Z1bW/SJAm+Vy1r5WtgwKL/RvKjU+GyzKrcfHTWVwtEjMw93JqlQOSBh
6OGQX0LR0f1UoClh5KHuSQKjEcCcB0mQSJLdtaWYRRluwKSCUu2IaZHQ/oabTpDP
6tg9bqKgAUqmfISicRvpjAVgTeB85DupoPwkOeOQ8GfEOsIsEAaBxdv2dzT+a5Bw
lOmXVu/65TCCyYzoWW8wOCKR+4SI6ibFPZ3MGwnsYLQn5SMAfVA79TcAWxgCnZUI
h/3lv1bMy4HY3HvnTnR5SkQ14I4qS8aRrKvupxNom8Asj4yFM9f7sQ1UphxNc7rM
yeZEXGI8zMczVdmr92f/F9uH8qRMd2Y6u1UgweCqjXPiTuWkQ+B+5nNQeUZ/cLxY
VSJWKKexvJiYWpOe7BE3toz0WrsszQIDAQABAoICAAuPETQIUtdU4OPAfwoo9YL0
WUWQMie+8sFMlm6dZpRr/XikU2UeluJHwB/jMYc3tGwknCeSG8hoWqMaA3HQhVRn
/XlRK3HnHcRxZKlMa2vaZcxei+dBCzJUC9IKAsYBOkf0q/0MN8Rvu6bjto/dl4yU
01U+WyEOUr9jYkIHRozmPBzyOad3K1ynzLeqejss8TWDXBFeqyli1nZKNHqDJafu
2Dh1Wrisb3ky24axCQ+wM2q0k4GX/jfOPawsqr0DjtqiJv8yHXLQzu+TD1hfQDwx
tdyovhgK0G8vKmrhbvWtEC0cFkKsD1bPZYStRa4jWhO0RrgPGz3ZvtykR7R5kZEU
+rVajFGVX4KRpiR3C2Gi7WqVwF4NIf6boNDSMDQ1YOEbQFYgXTWuS3IYJ6vfYwaC
QxjH70IOxHZzXQWmVHGc8HtR/FE2OJjZEkjd7fy8YDYD6bSo7ZEL1Bh34XfWoiUu
yMqhYsjgTrpftscrCIXR3w7nKd8KSm0+Bnk3VFARzQYm+yztdJ+t4XTi7oHW76we
Wv9t1R0/JyaxQuDYxoE958FDKXcXMv7WDWMocZx4gEXE7m2mzBXSNro5cecgKDip
4HDNxAh5TQBT4A8lVsVCZR3X7ls8LXZW60NLTCNlJNESDTtrdLF2Wk1/+O21Z9cw
B24RvY0ImA+oiJOFPBMhAoIBAQDjLdP7iHbD+/dEbsyLTN7Ru+29qe9u7CPJZLq3
1zGkGZ561jFRCHAXb9Ct0IigF65c7NCvu/n5cVuffdFjqhLq6fcyPOPJihIVqPkN
NzkD/jQZFvWpHwwhWForNFaZ3bd6kfGi5kia3CEZm/JDH9GbW6BUOHXAbXiBbTE6
eHm7B4fhIVfYNjjGeVzgD3WGMk95q2XKDJKCRmTsAmlUVNdQ37XAPl7aYtFCmYeX
NVAFsX5alaiOxfq/J/exrMvZRlkTjg/wr4tFC/yoLYkXQJSEWQlBfOkUUyi+37Rs
EGmPa6VfrcpLayoAkTQTdEuZYl5IfPXbUUOESc8Rjea5JqbVAoIBAQDD1UwQxJ41
5xlOariP+aj8/ntrUQKgOY7u91WZCgSJLWNvcOXvbQRsrq/6RNd0GyFBIziUk+t5
zwMoSbc9uERsbCsm8VYFAQulw43pMNHnCUdiMzQ252A1IIUPU+WGv3dWTPfMiT57
0p9j/lIXb2nSLXhLQHGJNu//tlvAP1KKx4+bfpzJgCw9lRPCgzZoY63E/6GYbDbF
diYylnrgPpvWuZGx5B7xJ88jV42qIIk3CJSkJ4gTtiHxU3AhFcnoOFMvf1aYRLfJ
eIPS2bBQFs6b7yswa+lNUEfvubHRP17slshTmc1Rf6mYHjrZ4WOhzAQAMwDOVLGc
dA6yBTd1FloZAoIBAEtUL91Q86iqzOPpJXPvSlcbTIq+ZYFPVdJ6zxsUhQZX5F/w
1Ct9c8Whsv1fj14eXBe+AriyyQG4X9wz2RGGHH2+lNQYsqNqX/LEs8h5DjPPv7Cu
F0k73UbVSBjZYvnkNemzqP8OAvculN8sAZnWXCd6q2Ah1JG4+uNXtKIhvqOQrLKu
3rT3zb2qEmzNU3frCMVcWwUzRAVkmCRV7F0lQLw1YcvcIpGhgKfnxrkR2XX5097v
jxPAfBOUiiJlHLbwB6tfSNPTMYf0oJOXfcSzCkwURehsJdEyfelEvkuy6X3AAPcH
5nM5lpTXkP/+aO70WjUJEnDlslCUNNAqUF4Gff0CggEAYXX97TptIpZo2cXzJHQz
zfU4pygiDmuW3wbo6sk5iKu2GPgu9wFielRV8E/iij4WRryopAkZ3/1OrPZC48yZ
APy0XSUukj769Pxl2/AYBstvY0fobIqqLsaIciBm0rDnS2PyzzBekHE6MiGX6WHh
YGCQxaLE3m0g9DplX0AkbDz1E4XnscDAQ8W1l9CFe15gVPKEEb+JYqxyRirt7Dw8
gpjIEaheXdZaGFSyhEC9CU6T6z5hUq4KJnhIDa8yVQfzHmhZSF6quPHpaT49qR4w
pRpafDa4XWne40efX2wSadyAxlp8/Fp0pOgmkdjCJPvL4e2AMS+lVR/NUHuYJgWB
wQKCAQBntVry4TRc4Jrq1L59/+j4qbbn33GrhASR4If5VqdFsEpLwAxRl62cqd7A
m9C0B2Vq7OquRVuqLsjHE9Ya6XkxCr3/FdrdCHxNwDdlMw2n+3vHH/GY1cMCgKQF
BV/buVbSV/+jKzoTTiWRKPC7QcRLGu3ctWywc9uWLleXIeR++fwaE4sZcXOc+Aza
tTCMtauJgNucc4+VrmTsQ4d+MDW+tXizOhTDn4SHtYStl97fdsee1qXC0/z/dN+J
zfChi35Hd1mREDEas5GxjX+MWiD4gTeb9+8UTfWv2p7nnBZpJ4krane0BbAREh9X
ZbWDNipnhC/tDlcGOjUmDDeG4i8O
    -----END RSA PRIVATE KEY-----

accounts:
  - iban: "CY02002001950000357023072713" # Your Bank of Cyprus IBAN
    ynab_account_id: "62de658a-275a-4ce9-b1d0-0de3a705d80c"
    aspsp_name: "bank_of_cyprus"
    country: "CY"
